### ISSUE TITLE
[scratchpad setSketch:image]; flips image 90 degres

### ISSUE THREAD

**Issue by Shasoosh** [dblapps/DAScratchPad#1]
Hey there,
Sometimes when I try to load a picture into my drawing area the picture flips 90 degres to the left. In other cases it flips 180 degres. Any idea what ia causing it?

This is what I added to your example project:

DAViewController.m:
<code>\- (IBAction)loadPic:(UIButton *)sender {
    UIImagePickerController *pickerLibrary = [[UIImagePickerController alloc] init];
    pickerLibrary.sourceType = UIImagePickerControllerSourceTypePhotoLibrary;
    pickerLibrary.delegate = self;
    [self presentModalViewController:pickerLibrary animated:YES];
}
- (void) imagePickerController:(UIImagePickerController *)picker didFinishPickingImage:(UIImage *)image editingInfo:(NSDictionary *)editingInfo
  {
  [self.scratchPad setSketch:image];
  [self dismissModalViewControllerAnimated:YES];
  }</code>

Also, how can i save the aspect ratio when loading a picture? it seems like the picture loads fine but changes aspect after first tap to draw on canvas.

**Comment by dblapps** [comment]
Hi Shasoosh,

The image rotation is almost certainly because DAScratchPad is not accounting for UIImage's imageOrientation.  I'll add in a fix for this.  Also, DAScratchPad currently assumes the image you load with setSketch: is the same size as the DAScratchPad view.  I'll also add something to scale as needed.  May not get to these changes for a week or so, though.

-Dave

**Comment by Shasoosh** [comment]
Thanks for the reply. What I did as a quick solution was to re scale the image according to its width (to keep the aspect ratio) and then change the Pad size according to the image size. Works pretty a good. :+1:

**Comment by dblapps** [comment]
Just checked in fixes for this.
